version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
    - te1
  assignees:
    - te1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
